version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/app/todo-manager/build
    overwrite: yes

permissions:
  - object: /
    pattern : "**"
    owner : root
    group: root


hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 180